from assets import ASSETS
from assets import FILE_NAME_OCTOPUS_H5 as FILE_NAME_READ
from assets import FILE_NAME_OCTOPUS
from assets import MODEL_NAME_OCTOPUS
N_BASIS = 4
FILE_NAME = FILE_NAME_OCTOPUS[N_BASIS]
MODEL_NAME = MODEL_NAME_OCTOPUS[0]